services:
  jwell-api:
    image: registry.digitalocean.com/alphart/alphart:jwell-api-latest
    pull_policy: always
    restart: unless-stopped
    ports:
      - "9527:3000"
    env_file: .env
    volumes:
      - ./data:/data
      - ./logs:/app/logs
    command: ["--log-dir", "/app/logs"]
